version: '2'

services:
  ca:
    container_name: ca.distributor.biswas.com
    extends:
      file: base.yaml
      service: ca-base
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca-distributor
    ports:
      - "10054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/ca.distributor.biswas.com-cert.pem --ca.keyfile /etc/hyperledger/8cd3d9a5696fc5f5b1345fecdce3fb1f73d9253887a561041f83833ca4ccbd85_sk -b admin:adminpw -d'
    volumes:
      - ../artifacts/certs/peerOrganizations/distributor.biswas.com/ca:/etc/hyperledger


  peer0-db:
    container_name: peer0-db.distributor.biswas.com
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=distributorpeer0admin
      - COUCHDB_PASSWORD=pass

  peer1-db:
    container_name: peer1-db.distributor.biswas.com
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=distributorpeer1admin
      - COUCHDB_PASSWORD=pass


  peer0:
    container_name: peer0.distributor.biswas.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.distributor.biswas.com
      - CORE_PEER_ADDRESS=peer0.distributor.biswas.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.distributor.biswas.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.distributor.biswas.com:7051
      - CORE_PEER_LOCALMSPID=DistributorMSP
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=peer0-db.distributor.biswas.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=distributorpeer0admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=pass
    volumes:
        - /var/run/:/host/var/run/
        - ../artifacts/certs/peerOrganizations/distributor.biswas.com/peers/peer0.distributor.biswas.com/msp:/etc/hyperledger/fabric/msp
    ports:
      - 13051:7051
      - 13053:7053

  peer1:
    container_name: peer1.distributor.biswas.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.distributor.biswas.com
      - CORE_PEER_ADDRESS=peer1.distributor.biswas.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.distributor.biswas.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.distributor.biswas.com:7051
      - CORE_PEER_LOCALMSPID=DistributorMSP
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=peer1-db.distributor.biswas.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=distributorpeer1admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=pass
    volumes:
        - /var/run/:/host/var/run/
        - ../artifacts/certs/peerOrganizations/distributor.biswas.com/peers/peer1.distributor.biswas.com/msp:/etc/hyperledger/fabric/msp
    ports:
      - 14051:7051
      - 14053:7053
